#!/usr/bin/env bash
# transfer file from client to server

reply="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ "$4" ]; then
   scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ]; then
     scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "$reply";
fi
