#!/bin/env bash
#ping 5 times

if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address="$1"

echo "PING $ip_address ($ip_address) 56(84) bytes of data."

for (( i=1; i<=5; i++ )); do
	ping_result=$(ping -c 1 "$ip_address" | awk '/bytes from/ {print}')
	echo "$ping_result"
done
