#!/bin/env bash
#List of interfaces and their addresses

ipv4_addresses=$(ifconfig | grep 'inet ' | cut -d ' ' -f 10)

# Use telnet and nc to get IPv4 addresses from localhost
local_ipv4=$(telnet localhost 23 2>/dev/null | grep 'Connected to' | cut -d ' ' -f 5)
local_ipv4_nc=$(nc -z -w 1 localhost 23 2>/dev/null && echo "127.0.0.1")

# Print the list of active IPv4 addresses

echo "$ipv4_addresses $local_ipv4 $local_ipv4_nc"
